services:
  database:
    image: postgres:17
    container_name: ecofinds_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecofinds
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./BACKEND
    container_name: ecofinds_backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/ecofinds
      - FLASK_ENV=development
      - SECRET_KEY=your-secure-flask-secret-key-change-in-production
      - JWT_SECRET_KEY=your-secure-jwt-secret-key-change-in-production
      - PORT=5000
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: ecofinds_frontend
    ports:
      - 3000:80
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: unless-stopped
